name: Deploy to EC2

on:
  push:
    branches:
      - develop  # develop 브랜치에 push될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'wafflestudio/23-5-team10-server'

    steps:
      # 1. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 자바 세팅 (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 권한 부여 (gradlew)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      # 5. EC2로 파일 전송
      - name: Transfer Jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 2 # 경로 떼고 파일만 옮기기

      # 6. EC2 접속해서 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          timeout: 60s
          command_timeout: 20m
          script: |
            # 기존에 실행 중인 자바 끄기 (없으면 패스)
            pgrep -f java | xargs -r kill -9 || true
            
            # 메모리 반환 10초 대기
            sleep 10
            
            # 새 파일이 있는 곳으로 이동
            cd /home/ubuntu/app
            
            # 실행 (로그는 nohup.out에 저장. 메모리 제한 400MB)
            nohup java -Xmx400m -jar *.jar > nohup.out 2>&1 &
            
            sleep 2
