name: Deploy to EC2

on:
  push:
    branches:
      - develop  # develop 브랜치에 push될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'wafflestudio/23-5-team10-server'

    steps:
      # 1. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 자바 세팅 (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 권한 부여 (gradlew)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test
        env:
          SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # 5. 기존 파일 지우기 (SCP 전송 전에 청소)
      - name: Clean up old jars
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: rm -rf /home/ubuntu/app/*.jar

      # 6. 새 파일 전송
      - name: Transfer Jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 2

      # 7. 배포 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          timeout: 60s
          command_timeout: 20m
          script: /home/ubuntu/deploy.sh
